#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Configuration for Gorge Chase PPO.
"""

import os


class Config:
    MAP_VIEW = 21
    MAP_CHANNELS = 6
    MAP_FLAT_LEN = MAP_CHANNELS * MAP_VIEW * MAP_VIEW

    SYM_FEATURE_SPLIT = [6, 10, 10, 9, 4, 8, 24, 16, 8, 8, 1, 4, 2, 2, 3]
    SYM_FEATURE_LEN = sum(SYM_FEATURE_SPLIT)
    DIM_OF_OBSERVATION = SYM_FEATURE_LEN

    ACTION_NUM = 16
    VALUE_NUM = 1

    GAMMA = 0.995
    LAMDA = 0.97
    INIT_LEARNING_RATE_START = 3e-4
    BETA_START = 0.02
    BETA_END = 0.005
    BETA_ANNEAL_STEPS = 2_000_000
    CLIP_PARAM = 0.2
    VF_COEF = 1.0
    GRAD_CLIP_RANGE = 0.5

    MAP_SIZE = 128.0
    MAX_MONSTER_SPEED = 2.0
    FLASH_RANGE_STRAIGHT = 10
    FLASH_RANGE_DIAGONAL = 8
    FLASH_COOLDOWN_DEFAULT = 100
    MAX_BUFF_DURATION = 50.0
    BFS_MAX_STEPS = 42

    DIR_OFFSETS = [
        (+1, 0),
        (+1, -1),
        (0, -1),
        (-1, -1),
        (-1, 0),
        (-1, +1),
        (0, +1),
        (+1, +1),
    ]
    FLASH_DISTANCES = [
        FLASH_RANGE_STRAIGHT,
        FLASH_RANGE_DIAGONAL,
        FLASH_RANGE_STRAIGHT,
        FLASH_RANGE_DIAGONAL,
        FLASH_RANGE_STRAIGHT,
        FLASH_RANGE_DIAGONAL,
        FLASH_RANGE_STRAIGHT,
        FLASH_RANGE_DIAGONAL,
    ]

    TOP_K_TREASURE = 3
    TOP_K_BUFF = 1

    TRAJECTORY_LEN = 10
    POSITION_HISTORY_WINDOW = 10

    R_TREASURE_EARLY = 2.0
    R_BUFF_EARLY = 0.5
    R_FLASH_TO_REACH = 0.3
    R_FLASH_COST_EARLY = -0.02
    R_SURVIVE_EARLY = 0.005

    R_TREASURE_LATE = 1.0
    R_BUFF_LATE = 0.3
    R_FLASH_ESCAPE = 0.8
    R_FLASH_WASTE_STAGE3 = -0.05
    R_FLASH_WASTE_STAGE4 = -0.25
    R_SURVIVE_LATE = 0.02
    R_FIRST_SEEN_TREASURE = 0.06
    R_OPENING_BLIND_TREASURE = -0.25

    R_BUMP_WALL = -0.1
    R_DEAD_END = -0.05
    R_WIN = 10.0
    R_FAIL = -10.0
    R_SCORE_SHAPED_COEF = 0.01

    POT_ALPHA_TREASURE = 0.3
    POT_BETA_MONSTER = 0.2

    MONSTER_DANGER_THRESHOLD = 6
    R_MONSTER_PROXIMITY_COEF = -0.35

    R_BUMP_WALL_TOWARD_UNREACHABLE = -0.3

    LINGER_STEP_LIMIT = 300
    LINGER_WINDOW = 10
    LINGER_L2_THRESHOLD = 5.0
    R_LINGER = -0.10

    OPENING_TREASURE_SHIELD_STEPS = 12
    OPENING_TREASURE_MONSTER_SAFE_DIST = 8

    RULE_ADJACENT_TREASURE = True
    RULE_PANIC_FLASH = True
    PANIC_FLASH_THRESHOLD_EARLY = 2
    PANIC_FLASH_THRESHOLD_LATE = 4
    CHASE_FLASH_THRESHOLD_LATE = 6
    FLASH_ESCAPE_MIN_GAIN = 2

    DEAD_END_RAY_THRESHOLD = 2
    DEAD_END_RATIO_THRESHOLD = 0.6

    CURRICULUM_AUTO = True
    STAGE_EPISODE_THRESHOLDS = [0, 2500, 5500]
    CURRICULUM_LOG_EVERY = 1
    CURRICULUM_STAGE_OVERRIDE = int(os.environ.get("CURRICULUM_STAGE_OVERRIDE", "0"))
    CURRICULUM_STAGE = 1
